
export const LOAD_PRODUCTS_BY_CATEGORY = 'LOAD_PRODUCTS_BY_CATEGORY';
export const ITEM_IN_CART_TOGGLE = 'ITEM_IN_CART_TOGGLE';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const ITEM_IN_WISH_LIST_TOGGLE = 'ITEM_IN_WISH_LIST_TOGGLE';
